name: nggoa
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
homepage: https://github.com/lazyee/flutter_gallery_3d
environment: {sdk: '>=2.18.6 <3.0.0'}
dependencies:
  flutter: {sdk: flutter} 
  flutter_lints: ^2.0.1
  provider: ^6.0.3
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  google_fonts: ^3.0.1
  path_provider: ^2.0.10
  smooth_page_indicator: ^1.0.0+2
  intl_phone_number_input: ^0.7.0+2
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  geocode: ^1.0.1
  google_place: ^0.4.7
  http: ^0.13.4
  get: ^4.6.1
  dio: ^4.0.0
  async: ^2.8.1
  focus_detector: ^2.0.0
  flutter_otp_text_field: ^1.0.0
  circular_bottom_navigation: ^2.0.0
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  flutter_share: ^2.0.0
  webview_flutter: ^3.0.4
  mobile_scanner: ^2.0.0
  flutter_custom_clippers: ^2.0.0
  share: 2.0.1
  flutter_typeahead: ^4.0.0
  url_launcher: ^6.1.5
  sliding_sheet: ^0.5.2
  image_picker: ^0.8.5+3
  filter_list: ^1.0.2
  flutter_svg: ^1.1.6
  syncfusion_flutter_datepicker: ^20.2.45
  permission_handler: ^10.0.0
  package_info_plus: ^1.4.2
  device_info_plus: ^3.1.1
  store_redirect: ^2.0.1
  otp_text_field: ^1.1.3
  cached_network_image: ^3.1.0
  flutter_html: ^3.0.0-alpha.3
  numeral: ^2.0.1
  toast: ^0.3.0
  fluttertoast: ^8.2.1
  expansion_tile_card: ^1.1.0
  multiselect: ^0.0.7
  flutter_local_notifications: ^9.3.1
  timezone: ^0.8.0
  file_picker: any
  flutter_inappwebview: ^5.7.2+3
  flutter_native_splash: ^2.2.5
  cupertino_icons: ^1.0.2
  page_indicator: ^0.4.1
  circle_nav_bar: ^2.0.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  #color: "#42a5f5"
  #brand_image: "assets/splash.png"
  #image: "assets/splash.png"
  background_image: "assets/background_imagee.png"
  fullscreen: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets: [assets/env/, assets/font/, assets/png/, assets/svg/]
  fonts:
  - fonts:
    - {asset: assets/font/Oswald-Bold.ttf}
    family: Oswald
  - fonts:
    - {asset: assets/font/Oswald-Light.ttf}
    family: Oswald
  - fonts:
    - {asset: assets/font/Oswald-Regular.ttf}
    family: Oswald
  - fonts:
    - {asset: assets/font/Oswald-VariableFont_wght.ttf}
    family: Oswald
  - fonts:
    - {asset: assets/font/Roboto-Bold.ttf}
    family: Roboto
  - fonts:
    - {asset: assets/font/Roboto-Light.ttf}
    family: Roboto
  - fonts:
    - {asset: assets/font/Roboto-Medium.ttf}
    family: Roboto
  - fonts:
    - {asset: assets/font/Roboto-Regular.ttf}
    family: Roboto
